#include <no_mali/dao/dao_gpu.h>
#include <no_mali/dao/dao_reg_op.h>

#include <mali_kbase.h>


void no_mali_init_reg(void) {
	
    int i = 0;
    for (i = 0; i < 4096; ++i) {
        no_mali_regs[i] = 0x00000000;
    }

    dao_reg_write(GPU_CONTROL_REG(GPU_ID), 0x62210001);
	dao_reg_write(GPU_CONTROL_REG(L2_FEATURES), 0x07130206);
	dao_reg_write(GPU_CONTROL_REG(SUSPEND_SIZE), 0x00000000);
	dao_reg_write(GPU_CONTROL_REG(TILER_FEATURES), 0x00000809);
	dao_reg_write(GPU_CONTROL_REG(MEM_FEATURES), 0x00000101);
	dao_reg_write(GPU_CONTROL_REG(MMU_FEATURES), 0x00002830);
	dao_reg_write(GPU_CONTROL_REG(AS_PRESENT), 0x000000ff);
	dao_reg_write(GPU_CONTROL_REG(JS_PRESENT), 0x00000007);

	dao_reg_write(JS_FEATURES_REG(0), 0x0000020e);
	dao_reg_write(JS_FEATURES_REG(1), 0x000004fe);
	dao_reg_write(JS_FEATURES_REG(2), 0x0000007e);
	dao_reg_write(JS_FEATURES_REG(3), 0x00000000);
	dao_reg_write(JS_FEATURES_REG(4), 0x00000000);
	dao_reg_write(JS_FEATURES_REG(5), 0x00000000);
	dao_reg_write(JS_FEATURES_REG(6), 0x00000000);
	dao_reg_write(JS_FEATURES_REG(7), 0x00000000);
	dao_reg_write(JS_FEATURES_REG(8), 0x00000000);
	dao_reg_write(JS_FEATURES_REG(9), 0x00000000);
	dao_reg_write(JS_FEATURES_REG(10), 0x00000000);
	dao_reg_write(JS_FEATURES_REG(11), 0x00000000);
	dao_reg_write(JS_FEATURES_REG(12), 0x00000000);
	dao_reg_write(JS_FEATURES_REG(13), 0x00000000);
	dao_reg_write(JS_FEATURES_REG(14), 0x00000000);
	dao_reg_write(JS_FEATURES_REG(15), 0x00000000);

	dao_reg_write(TEXTURE_FEATURES_REG(0), 0xffffffff);
	dao_reg_write(TEXTURE_FEATURES_REG(1), 0x00ff0fff);
	dao_reg_write(TEXTURE_FEATURES_REG(2), 0xfe3fffff);
	dao_reg_write(TEXTURE_FEATURES_REG(3), 0x00000000);

	dao_reg_write(GPU_CONTROL_REG(THREAD_MAX_THREADS), 0x00000180);
	dao_reg_write(GPU_CONTROL_REG(THREAD_MAX_WORKGROUP_SIZE), 0x00000180);
	dao_reg_write(GPU_CONTROL_REG(THREAD_MAX_BARRIER_SIZE), 0x00000180);
	dao_reg_write(GPU_CONTROL_REG(THREAD_FEATURES), 0x0a046000);

	dao_reg_write(GPU_CONTROL_REG(SHADER_PRESENT_LO), 0x00000fff);
	dao_reg_write(GPU_CONTROL_REG(SHADER_PRESENT_HI), 0x00000000);
	dao_reg_write(GPU_CONTROL_REG(TILER_PRESENT_LO), 0x00000001);
	dao_reg_write(GPU_CONTROL_REG(TILER_PRESENT_HI), 0x00000000);

	dao_reg_write(GPU_CONTROL_REG(L2_PRESENT_LO), 0x00000001);
	dao_reg_write(GPU_CONTROL_REG(L2_PRESENT_HI), 0x00000000);

	dao_reg_write(GPU_CONTROL_REG(STACK_PRESENT_LO), 0x0000000f);
	dao_reg_write(GPU_CONTROL_REG(STACK_PRESENT_HI), 0x00000000);

	dao_reg_write(GPU_CONTROL_REG(COHERENCY_FEATURES), 0x00000002); 

	dao_reg_write(GPU_CONTROL_REG(L2_MMU_CONFIG), 0x00800000); 
	dao_reg_write(GPU_CONTROL_REG(SHADER_CONFIG), 0x00000000); 
	dao_reg_write(GPU_CONTROL_REG(TILER_CONFIG), 0x00000000); 
	dao_reg_write(GPU_CONTROL_REG(JM_CONFIG), 0x00000000); 
 
}



void no_mali_reg_names(void) {
	
    no_mali_reg_name[0] = "GPU_ID";
    no_mali_reg_name[1] = "L2_FEATURES";
    no_mali_reg_name[2] = "SUSPEND_SIZE";
    no_mali_reg_name[3] = "TILER_FEATURES";
    no_mali_reg_name[4] = "MEM_FEATURES";
    no_mali_reg_name[5] = "MMU_FEATURES";
    no_mali_reg_name[6] = "AS_PRESENT";
    no_mali_reg_name[7] = "JS_PRESENT"; 
    no_mali_reg_name[8] = "GPU_IRQ_RAWSTAT";
    no_mali_reg_name[9] = "GPU_IRQ_CLEAR";
    no_mali_reg_name[10] = "GPU_IRQ_MASK";
    no_mali_reg_name[11] = "GPU_IRQ_STATUS";
    no_mali_reg_name[12] = "GPU_COMMAND";
    no_mali_reg_name[13] = "GPU_STATUS";
    no_mali_reg_name[14] = "LATEST_FLUSH";
    no_mali_reg_name[15] = "GPU_FAULTSTATUS";
    no_mali_reg_name[16] = "GPU_FAULTADDRESS_LO";
    no_mali_reg_name[17] = "GPU_FAULTADDRESS_HI";
    no_mali_reg_name[20] = "PWR_KEY";
    no_mali_reg_name[21] = "PWR_OVERRIDE0";
    no_mali_reg_name[22] = "PWR_OVERRIDE1";
    no_mali_reg_name[24] = "PRFCNT_BASE_LO";
    no_mali_reg_name[25] = "PRFCNT_BASE_HI";
    no_mali_reg_name[26] = "PRFCNT_CONFIG";
    no_mali_reg_name[27] = "PRFCNT_JM_EN";
    no_mali_reg_name[28] = "PRFCNT_SHADER_EN";
    no_mali_reg_name[29] = "PRFCNT_TILER_EN";
    no_mali_reg_name[31] = "PRFCNT_MMU_L2_EN";
    no_mali_reg_name[36] = "CYCLE_COUNT_LO";
    no_mali_reg_name[37] = "CYCLE_COUNT_HI";
    no_mali_reg_name[38] = "TIMESTAMP_LO";
    no_mali_reg_name[39] = "TIMESTAMP_HI";
    no_mali_reg_name[40] = "THREAD_MAX_THREADS";
    no_mali_reg_name[41] = "THREAD_MAX_WORKGROUP_SIZE";
    no_mali_reg_name[42] = "THREAD_MAX_BARRIER_SIZE";
    no_mali_reg_name[43] = "THREAD_FEATURES";
    no_mali_reg_name[44] = "TEXTURE_FEATURES_0";
    no_mali_reg_name[45] = "TEXTURE_FEATURES_1";
    no_mali_reg_name[46] = "TEXTURE_FEATURES_2";
    no_mali_reg_name[47] = "TEXTURE_FEATURES_3";
    no_mali_reg_name[48] = "JS0_FEATURES";
    no_mali_reg_name[49] = "JS1_FEATURES";
    no_mali_reg_name[50] = "JS2_FEATURES";
    no_mali_reg_name[51] = "JS3_FEATURES";
    no_mali_reg_name[52] = "JS4_FEATURES";
    no_mali_reg_name[53] = "JS5_FEATURES";
    no_mali_reg_name[54] = "JS6_FEATURES";
    no_mali_reg_name[55] = "JS7_FEATURES";
    no_mali_reg_name[56] = "JS8_FEATURES";
    no_mali_reg_name[57] = "JS9_FEATURES";
    no_mali_reg_name[58] = "JS10_FEATURES";
    no_mali_reg_name[59] = "JS11_FEATURES";
    no_mali_reg_name[60] = "JS12_FEATURES";
    no_mali_reg_name[61] = "JS13_FEATURES";
    no_mali_reg_name[62] = "JS14_FEATURES";
    no_mali_reg_name[63] = "JS15_FEATURES";
    no_mali_reg_name[64] = "SHADER_PRESENT_LO";
    no_mali_reg_name[65] = "SHADER_PRESENT_HI";
    no_mali_reg_name[68] = "TILER_PRESENT_LO";
    no_mali_reg_name[69] = "TILER_PRESENT_HI";
    no_mali_reg_name[72] = "L2_PRESENT_LO";
    no_mali_reg_name[73] = "L2_PRESENT_HI";
    no_mali_reg_name[896] = "STACK_PRESENT_LO";
    no_mali_reg_name[897] = "STACK_PRESENT_HI";
    no_mali_reg_name[80] = "SHADER_READY_LO";
    no_mali_reg_name[81] = "SHADER_READY_HI";
    no_mali_reg_name[84] = "TILER_READY_LO";
    no_mali_reg_name[85] = "TILER_READY_HI";
    no_mali_reg_name[88] = "L2_READY_LO";
    no_mali_reg_name[89] = "L2_READY_HI";
    no_mali_reg_name[900] = "STACK_READY_LO";
    no_mali_reg_name[901] = "STACK_READY_HI";
    no_mali_reg_name[96] = "SHADER_PWRON_LO";
    no_mali_reg_name[97] = "SHADER_PWRON_HI";
    no_mali_reg_name[100] = "TILER_PWRON_LO";
    no_mali_reg_name[101] = "TILER_PWRON_HI";
    no_mali_reg_name[104] = "L2_PWRON_LO";
    no_mali_reg_name[105] = "L2_PWRON_HI";
    no_mali_reg_name[904] = "STACK_PWRON_LO";
    no_mali_reg_name[905] = "STACK_PWRON_HI";
    no_mali_reg_name[112] = "SHADER_PWROFF_LO";
    no_mali_reg_name[113] = "SHADER_PWROFF_HI";
    no_mali_reg_name[116] = "TILER_PWROFF_LO";
    no_mali_reg_name[117] = "TILER_PWROFF_HI";
    no_mali_reg_name[120] = "L2_PWROFF_LO";
    no_mali_reg_name[121] = "L2_PWROFF_HI";
    no_mali_reg_name[908] = "STACK_PWROFF_LO";
    no_mali_reg_name[909] = "STACK_PWROFF_HI";
    no_mali_reg_name[128] = "SHADER_PWRTRANS_LO";
    no_mali_reg_name[129] = "SHADER_PWRTRANS_HI";
    no_mali_reg_name[132] = "TILER_PWRTRANS_LO";
    no_mali_reg_name[133] = "TILER_PWRTRANS_HI";
    no_mali_reg_name[136] = "L2_PWRTRANS_LO";
    no_mali_reg_name[137] = "L2_PWRTRANS_HI";
    no_mali_reg_name[912] = "STACK_PWRTRANS_LO";
    no_mali_reg_name[913] = "STACK_PWRTRANS_HI";
    no_mali_reg_name[144] = "SHADER_PWRACTIVE_LO";
    no_mali_reg_name[145] = "SHADER_PWRACTIVE_HI";
    no_mali_reg_name[148] = "TILER_PWRACTIVE_LO";
    no_mali_reg_name[149] = "TILER_PWRACTIVE_HI";
    no_mali_reg_name[152] = "L2_PWRACTIVE_LO";
    no_mali_reg_name[153] = "L2_PWRACTIVE_HI";
    no_mali_reg_name[192] = "COHERENCY_FEATURES";
    no_mali_reg_name[193] = "COHERENCY_ENABLE";
    no_mali_reg_name[960] = "JM_CONFIG";
    no_mali_reg_name[961] = "SHADER_CONFIG";
    no_mali_reg_name[962] = "TILER_CONFIG";
    no_mali_reg_name[963] = "L2_MMU_CONFIG";


    no_mali_reg_name[1024] = "JOB_IRQ_RAWSTAT";
    no_mali_reg_name[1025] = "JOB_IRQ_CLEAR";
    no_mali_reg_name[1026] = "JOB_IRQ_MASK";
    no_mali_reg_name[1027] = "JOB_IRQ_STATUS";
    no_mali_reg_name[1028] = "JOB_IRQ_JS_STATE";
    no_mali_reg_name[1029] = "JOB_IRQ_THROTTLE";
    no_mali_reg_name[1536] = "JOB_SLOT0_JS_HEAD_LO";
    no_mali_reg_name[1537] = "JOB_SLOT0_JS_HEAD_HI";
    no_mali_reg_name[1538] = "JOB_SLOT0_JS_TAIL_LO";
    no_mali_reg_name[1539] = "JOB_SLOT0_JS_TAIL_HI";
    no_mali_reg_name[1540] = "JOB_SLOT0_JS_AFFINITY_LO";
    no_mali_reg_name[1541] = "JOB_SLOT0_JS_AFFINITY_HI";
    no_mali_reg_name[1542] = "JOB_SLOT0_JS_CONFIG";
    no_mali_reg_name[1543] = "JOB_SLOT0_JS_XAFFINITY";
    no_mali_reg_name[1544] = "JOB_SLOT0_JS_COMMAND";
    no_mali_reg_name[1545] = "JOB_SLOT0_JS_STATUS";
    no_mali_reg_name[1552] = "JOB_SLOT0_JS_HEAD_NEXT_LO";
    no_mali_reg_name[1553] = "JOB_SLOT0_JS_HEAD_NEXT_HI";
    no_mali_reg_name[1556] = "JOB_SLOT0_JS_AFFINITY_NEXT_LO";
    no_mali_reg_name[1557] = "JOB_SLOT0_JS_AFFINITY_NEXT_HI";
    no_mali_reg_name[1558] = "JOB_SLOT0_JS_CONFIG_NEXT";
    no_mali_reg_name[1559] = "JOB_SLOT0_JS_XAFFINITY_NEXT";
    no_mali_reg_name[1560] = "JOB_SLOT0_JS_COMMAND_NEXT";
    no_mali_reg_name[1564] = "JOB_SLOT0_JS_FLUSH_ID_NEXT";
    no_mali_reg_name[1568] = "JOB_SLOT1_JS_HEAD_LO";
    no_mali_reg_name[1569] = "JOB_SLOT1_JS_HEAD_HI";
    no_mali_reg_name[1570] = "JOB_SLOT1_JS_TAIL_LO";
    no_mali_reg_name[1571] = "JOB_SLOT1_JS_TAIL_HI";
    no_mali_reg_name[1572] = "JOB_SLOT1_JS_AFFINITY_LO";
    no_mali_reg_name[1573] = "JOB_SLOT1_JS_AFFINITY_HI";
    no_mali_reg_name[1574] = "JOB_SLOT1_JS_CONFIG";
    no_mali_reg_name[1575] = "JOB_SLOT1_JS_XAFFINITY";
    no_mali_reg_name[1576] = "JOB_SLOT1_JS_COMMAND";
    no_mali_reg_name[1577] = "JOB_SLOT1_JS_STATUS";
    no_mali_reg_name[1584] = "JOB_SLOT1_JS_HEAD_NEXT_LO";
    no_mali_reg_name[1585] = "JOB_SLOT1_JS_HEAD_NEXT_HI";
    no_mali_reg_name[1588] = "JOB_SLOT1_JS_AFFINITY_NEXT_LO";
    no_mali_reg_name[1589] = "JOB_SLOT1_JS_AFFINITY_NEXT_HI";
    no_mali_reg_name[1590] = "JOB_SLOT1_JS_CONFIG_NEXT";
    no_mali_reg_name[1591] = "JOB_SLOT1_JS_XAFFINITY_NEXT";
    no_mali_reg_name[1592] = "JOB_SLOT1_JS_COMMAND_NEXT";
    no_mali_reg_name[1596] = "JOB_SLOT1_JS_FLUSH_ID_NEXT";
    no_mali_reg_name[1600] = "JOB_SLOT2_JS_HEAD_LO";
    no_mali_reg_name[1601] = "JOB_SLOT2_JS_HEAD_HI";
    no_mali_reg_name[1602] = "JOB_SLOT2_JS_TAIL_LO";
    no_mali_reg_name[1603] = "JOB_SLOT2_JS_TAIL_HI";
    no_mali_reg_name[1604] = "JOB_SLOT2_JS_AFFINITY_LO";
    no_mali_reg_name[1605] = "JOB_SLOT2_JS_AFFINITY_HI";
    no_mali_reg_name[1606] = "JOB_SLOT2_JS_CONFIG";
    no_mali_reg_name[1607] = "JOB_SLOT2_JS_XAFFINITY";
    no_mali_reg_name[1608] = "JOB_SLOT2_JS_COMMAND";
    no_mali_reg_name[1609] = "JOB_SLOT2_JS_STATUS";
    no_mali_reg_name[1616] = "JOB_SLOT2_JS_HEAD_NEXT_LO";
    no_mali_reg_name[1617] = "JOB_SLOT2_JS_HEAD_NEXT_HI";
    no_mali_reg_name[1620] = "JOB_SLOT2_JS_AFFINITY_NEXT_LO";
    no_mali_reg_name[1621] = "JOB_SLOT2_JS_AFFINITY_NEXT_HI";
    no_mali_reg_name[1622] = "JOB_SLOT2_JS_CONFIG_NEXT";
    no_mali_reg_name[1623] = "JOB_SLOT2_JS_XAFFINITY_NEXT";
    no_mali_reg_name[1624] = "JOB_SLOT2_JS_COMMAND_NEXT";
    no_mali_reg_name[1628] = "JOB_SLOT2_JS_FLUSH_ID_NEXT";
    no_mali_reg_name[1632] = "JOB_SLOT3_JS_HEAD_LO";
    no_mali_reg_name[1633] = "JOB_SLOT3_JS_HEAD_HI";
    no_mali_reg_name[1634] = "JOB_SLOT3_JS_TAIL_LO";
    no_mali_reg_name[1635] = "JOB_SLOT3_JS_TAIL_HI";
    no_mali_reg_name[1636] = "JOB_SLOT3_JS_AFFINITY_LO";
    no_mali_reg_name[1637] = "JOB_SLOT3_JS_AFFINITY_HI";
    no_mali_reg_name[1638] = "JOB_SLOT3_JS_CONFIG";
    no_mali_reg_name[1639] = "JOB_SLOT3_JS_XAFFINITY";
    no_mali_reg_name[1640] = "JOB_SLOT3_JS_COMMAND";
    no_mali_reg_name[1641] = "JOB_SLOT3_JS_STATUS";
    no_mali_reg_name[1648] = "JOB_SLOT3_JS_HEAD_NEXT_LO";
    no_mali_reg_name[1649] = "JOB_SLOT3_JS_HEAD_NEXT_HI";
    no_mali_reg_name[1652] = "JOB_SLOT3_JS_AFFINITY_NEXT_LO";
    no_mali_reg_name[1653] = "JOB_SLOT3_JS_AFFINITY_NEXT_HI";
    no_mali_reg_name[1654] = "JOB_SLOT3_JS_CONFIG_NEXT";
    no_mali_reg_name[1655] = "JOB_SLOT3_JS_XAFFINITY_NEXT";
    no_mali_reg_name[1656] = "JOB_SLOT3_JS_COMMAND_NEXT";
    no_mali_reg_name[1660] = "JOB_SLOT3_JS_FLUSH_ID_NEXT";
    no_mali_reg_name[1664] = "JOB_SLOT4_JS_HEAD_LO";
    no_mali_reg_name[1665] = "JOB_SLOT4_JS_HEAD_HI";
    no_mali_reg_name[1666] = "JOB_SLOT4_JS_TAIL_LO";
    no_mali_reg_name[1667] = "JOB_SLOT4_JS_TAIL_HI";
    no_mali_reg_name[1668] = "JOB_SLOT4_JS_AFFINITY_LO";
    no_mali_reg_name[1669] = "JOB_SLOT4_JS_AFFINITY_HI";
    no_mali_reg_name[1670] = "JOB_SLOT4_JS_CONFIG";
    no_mali_reg_name[1671] = "JOB_SLOT4_JS_XAFFINITY";
    no_mali_reg_name[1672] = "JOB_SLOT4_JS_COMMAND";
    no_mali_reg_name[1673] = "JOB_SLOT4_JS_STATUS";
    no_mali_reg_name[1680] = "JOB_SLOT4_JS_HEAD_NEXT_LO";
    no_mali_reg_name[1681] = "JOB_SLOT4_JS_HEAD_NEXT_HI";
    no_mali_reg_name[1684] = "JOB_SLOT4_JS_AFFINITY_NEXT_LO";
    no_mali_reg_name[1685] = "JOB_SLOT4_JS_AFFINITY_NEXT_HI";
    no_mali_reg_name[1686] = "JOB_SLOT4_JS_CONFIG_NEXT";
    no_mali_reg_name[1687] = "JOB_SLOT4_JS_XAFFINITY_NEXT";
    no_mali_reg_name[1688] = "JOB_SLOT4_JS_COMMAND_NEXT";
    no_mali_reg_name[1692] = "JOB_SLOT4_JS_FLUSH_ID_NEXT";
    no_mali_reg_name[1696] = "JOB_SLOT5_JS_HEAD_LO";
    no_mali_reg_name[1697] = "JOB_SLOT5_JS_HEAD_HI";
    no_mali_reg_name[1698] = "JOB_SLOT5_JS_TAIL_LO";
    no_mali_reg_name[1699] = "JOB_SLOT5_JS_TAIL_HI";
    no_mali_reg_name[1700] = "JOB_SLOT5_JS_AFFINITY_LO";
    no_mali_reg_name[1701] = "JOB_SLOT5_JS_AFFINITY_HI";
    no_mali_reg_name[1702] = "JOB_SLOT5_JS_CONFIG";
    no_mali_reg_name[1703] = "JOB_SLOT5_JS_XAFFINITY";
    no_mali_reg_name[1704] = "JOB_SLOT5_JS_COMMAND";
    no_mali_reg_name[1705] = "JOB_SLOT5_JS_STATUS";
    no_mali_reg_name[1712] = "JOB_SLOT5_JS_HEAD_NEXT_LO";
    no_mali_reg_name[1713] = "JOB_SLOT5_JS_HEAD_NEXT_HI";
    no_mali_reg_name[1716] = "JOB_SLOT5_JS_AFFINITY_NEXT_LO";
    no_mali_reg_name[1717] = "JOB_SLOT5_JS_AFFINITY_NEXT_HI";
    no_mali_reg_name[1718] = "JOB_SLOT5_JS_CONFIG_NEXT";
    no_mali_reg_name[1719] = "JOB_SLOT5_JS_XAFFINITY_NEXT";
    no_mali_reg_name[1720] = "JOB_SLOT5_JS_COMMAND_NEXT";
    no_mali_reg_name[1724] = "JOB_SLOT5_JS_FLUSH_ID_NEXT";
    no_mali_reg_name[1728] = "JOB_SLOT6_JS_HEAD_LO";
    no_mali_reg_name[1729] = "JOB_SLOT6_JS_HEAD_HI";
    no_mali_reg_name[1730] = "JOB_SLOT6_JS_TAIL_LO";
    no_mali_reg_name[1731] = "JOB_SLOT6_JS_TAIL_HI";
    no_mali_reg_name[1732] = "JOB_SLOT6_JS_AFFINITY_LO";
    no_mali_reg_name[1733] = "JOB_SLOT6_JS_AFFINITY_HI";
    no_mali_reg_name[1734] = "JOB_SLOT6_JS_CONFIG";
    no_mali_reg_name[1735] = "JOB_SLOT6_JS_XAFFINITY";
    no_mali_reg_name[1736] = "JOB_SLOT6_JS_COMMAND";
    no_mali_reg_name[1737] = "JOB_SLOT6_JS_STATUS";
    no_mali_reg_name[1744] = "JOB_SLOT6_JS_HEAD_NEXT_LO";
    no_mali_reg_name[1745] = "JOB_SLOT6_JS_HEAD_NEXT_HI";
    no_mali_reg_name[1748] = "JOB_SLOT6_JS_AFFINITY_NEXT_LO";
    no_mali_reg_name[1749] = "JOB_SLOT6_JS_AFFINITY_NEXT_HI";
    no_mali_reg_name[1750] = "JOB_SLOT6_JS_CONFIG_NEXT";
    no_mali_reg_name[1751] = "JOB_SLOT6_JS_XAFFINITY_NEXT";
    no_mali_reg_name[1752] = "JOB_SLOT6_JS_COMMAND_NEXT";
    no_mali_reg_name[1756] = "JOB_SLOT6_JS_FLUSH_ID_NEXT";
    no_mali_reg_name[1760] = "JOB_SLOT7_JS_HEAD_LO";
    no_mali_reg_name[1761] = "JOB_SLOT7_JS_HEAD_HI";
    no_mali_reg_name[1762] = "JOB_SLOT7_JS_TAIL_LO";
    no_mali_reg_name[1763] = "JOB_SLOT7_JS_TAIL_HI";
    no_mali_reg_name[1764] = "JOB_SLOT7_JS_AFFINITY_LO";
    no_mali_reg_name[1765] = "JOB_SLOT7_JS_AFFINITY_HI";
    no_mali_reg_name[1766] = "JOB_SLOT7_JS_CONFIG";
    no_mali_reg_name[1767] = "JOB_SLOT7_JS_XAFFINITY";
    no_mali_reg_name[1768] = "JOB_SLOT7_JS_COMMAND";
    no_mali_reg_name[1769] = "JOB_SLOT7_JS_STATUS";
    no_mali_reg_name[1776] = "JOB_SLOT7_JS_HEAD_NEXT_LO";
    no_mali_reg_name[1777] = "JOB_SLOT7_JS_HEAD_NEXT_HI";
    no_mali_reg_name[1780] = "JOB_SLOT7_JS_AFFINITY_NEXT_LO";
    no_mali_reg_name[1781] = "JOB_SLOT7_JS_AFFINITY_NEXT_HI";
    no_mali_reg_name[1782] = "JOB_SLOT7_JS_CONFIG_NEXT";
    no_mali_reg_name[1783] = "JOB_SLOT7_JS_XAFFINITY_NEXT";
    no_mali_reg_name[1784] = "JOB_SLOT7_JS_COMMAND_NEXT";
    no_mali_reg_name[1788] = "JOB_SLOT7_JS_FLUSH_ID_NEXT";
    no_mali_reg_name[1792] = "JOB_SLOT8_JS_HEAD_LO";
    no_mali_reg_name[1793] = "JOB_SLOT8_JS_HEAD_HI";
    no_mali_reg_name[1794] = "JOB_SLOT8_JS_TAIL_LO";
    no_mali_reg_name[1795] = "JOB_SLOT8_JS_TAIL_HI";
    no_mali_reg_name[1796] = "JOB_SLOT8_JS_AFFINITY_LO";
    no_mali_reg_name[1797] = "JOB_SLOT8_JS_AFFINITY_HI";
    no_mali_reg_name[1798] = "JOB_SLOT8_JS_CONFIG";
    no_mali_reg_name[1799] = "JOB_SLOT8_JS_XAFFINITY";
    no_mali_reg_name[1800] = "JOB_SLOT8_JS_COMMAND";
    no_mali_reg_name[1801] = "JOB_SLOT8_JS_STATUS";
    no_mali_reg_name[1808] = "JOB_SLOT8_JS_HEAD_NEXT_LO";
    no_mali_reg_name[1809] = "JOB_SLOT8_JS_HEAD_NEXT_HI";
    no_mali_reg_name[1812] = "JOB_SLOT8_JS_AFFINITY_NEXT_LO";
    no_mali_reg_name[1813] = "JOB_SLOT8_JS_AFFINITY_NEXT_HI";
    no_mali_reg_name[1814] = "JOB_SLOT8_JS_CONFIG_NEXT";
    no_mali_reg_name[1815] = "JOB_SLOT8_JS_XAFFINITY_NEXT";
    no_mali_reg_name[1816] = "JOB_SLOT8_JS_COMMAND_NEXT";
    no_mali_reg_name[1820] = "JOB_SLOT8_JS_FLUSH_ID_NEXT";
    no_mali_reg_name[1824] = "JOB_SLOT9_JS_HEAD_LO";
    no_mali_reg_name[1825] = "JOB_SLOT9_JS_HEAD_HI";
    no_mali_reg_name[1826] = "JOB_SLOT9_JS_TAIL_LO";
    no_mali_reg_name[1827] = "JOB_SLOT9_JS_TAIL_HI";
    no_mali_reg_name[1828] = "JOB_SLOT9_JS_AFFINITY_LO";
    no_mali_reg_name[1829] = "JOB_SLOT9_JS_AFFINITY_HI";
    no_mali_reg_name[1830] = "JOB_SLOT9_JS_CONFIG";
    no_mali_reg_name[1831] = "JOB_SLOT9_JS_XAFFINITY";
    no_mali_reg_name[1832] = "JOB_SLOT9_JS_COMMAND";
    no_mali_reg_name[1833] = "JOB_SLOT9_JS_STATUS";
    no_mali_reg_name[1840] = "JOB_SLOT9_JS_HEAD_NEXT_LO";
    no_mali_reg_name[1841] = "JOB_SLOT9_JS_HEAD_NEXT_HI";
    no_mali_reg_name[1844] = "JOB_SLOT9_JS_AFFINITY_NEXT_LO";
    no_mali_reg_name[1845] = "JOB_SLOT9_JS_AFFINITY_NEXT_HI";
    no_mali_reg_name[1846] = "JOB_SLOT9_JS_CONFIG_NEXT";
    no_mali_reg_name[1847] = "JOB_SLOT9_JS_XAFFINITY_NEXT";
    no_mali_reg_name[1848] = "JOB_SLOT9_JS_COMMAND_NEXT";
    no_mali_reg_name[1852] = "JOB_SLOT9_JS_FLUSH_ID_NEXT";
    no_mali_reg_name[1856] = "JOB_SLOT10_JS_HEAD_LO";
    no_mali_reg_name[1857] = "JOB_SLOT10_JS_HEAD_HI";
    no_mali_reg_name[1858] = "JOB_SLOT10_JS_TAIL_LO";
    no_mali_reg_name[1859] = "JOB_SLOT10_JS_TAIL_HI";
    no_mali_reg_name[1860] = "JOB_SLOT10_JS_AFFINITY_LO";
    no_mali_reg_name[1861] = "JOB_SLOT10_JS_AFFINITY_HI";
    no_mali_reg_name[1862] = "JOB_SLOT10_JS_CONFIG";
    no_mali_reg_name[1863] = "JOB_SLOT10_JS_XAFFINITY";
    no_mali_reg_name[1864] = "JOB_SLOT10_JS_COMMAND";
    no_mali_reg_name[1865] = "JOB_SLOT10_JS_STATUS";
    no_mali_reg_name[1872] = "JOB_SLOT10_JS_HEAD_NEXT_LO";
    no_mali_reg_name[1873] = "JOB_SLOT10_JS_HEAD_NEXT_HI";
    no_mali_reg_name[1876] = "JOB_SLOT10_JS_AFFINITY_NEXT_LO";
    no_mali_reg_name[1877] = "JOB_SLOT10_JS_AFFINITY_NEXT_HI";
    no_mali_reg_name[1878] = "JOB_SLOT10_JS_CONFIG_NEXT";
    no_mali_reg_name[1879] = "JOB_SLOT10_JS_XAFFINITY_NEXT";
    no_mali_reg_name[1880] = "JOB_SLOT10_JS_COMMAND_NEXT";
    no_mali_reg_name[1884] = "JOB_SLOT10_JS_FLUSH_ID_NEXT";
    no_mali_reg_name[1888] = "JOB_SLOT11_JS_HEAD_LO";
    no_mali_reg_name[1889] = "JOB_SLOT11_JS_HEAD_HI";
    no_mali_reg_name[1890] = "JOB_SLOT11_JS_TAIL_LO";
    no_mali_reg_name[1891] = "JOB_SLOT11_JS_TAIL_HI";
    no_mali_reg_name[1892] = "JOB_SLOT11_JS_AFFINITY_LO";
    no_mali_reg_name[1893] = "JOB_SLOT11_JS_AFFINITY_HI";
    no_mali_reg_name[1894] = "JOB_SLOT11_JS_CONFIG";
    no_mali_reg_name[1895] = "JOB_SLOT11_JS_XAFFINITY";
    no_mali_reg_name[1896] = "JOB_SLOT11_JS_COMMAND";
    no_mali_reg_name[1897] = "JOB_SLOT11_JS_STATUS";
    no_mali_reg_name[1904] = "JOB_SLOT11_JS_HEAD_NEXT_LO";
    no_mali_reg_name[1905] = "JOB_SLOT11_JS_HEAD_NEXT_HI";
    no_mali_reg_name[1908] = "JOB_SLOT11_JS_AFFINITY_NEXT_LO";
    no_mali_reg_name[1909] = "JOB_SLOT11_JS_AFFINITY_NEXT_HI";
    no_mali_reg_name[1910] = "JOB_SLOT11_JS_CONFIG_NEXT";
    no_mali_reg_name[1911] = "JOB_SLOT11_JS_XAFFINITY_NEXT";
    no_mali_reg_name[1912] = "JOB_SLOT11_JS_COMMAND_NEXT";
    no_mali_reg_name[1916] = "JOB_SLOT11_JS_FLUSH_ID_NEXT";
    no_mali_reg_name[1920] = "JOB_SLOT12_JS_HEAD_LO";
    no_mali_reg_name[1921] = "JOB_SLOT12_JS_HEAD_HI";
    no_mali_reg_name[1922] = "JOB_SLOT12_JS_TAIL_LO";
    no_mali_reg_name[1923] = "JOB_SLOT12_JS_TAIL_HI";
    no_mali_reg_name[1924] = "JOB_SLOT12_JS_AFFINITY_LO";
    no_mali_reg_name[1925] = "JOB_SLOT12_JS_AFFINITY_HI";
    no_mali_reg_name[1926] = "JOB_SLOT12_JS_CONFIG";
    no_mali_reg_name[1927] = "JOB_SLOT12_JS_XAFFINITY";
    no_mali_reg_name[1928] = "JOB_SLOT12_JS_COMMAND";
    no_mali_reg_name[1929] = "JOB_SLOT12_JS_STATUS";
    no_mali_reg_name[1936] = "JOB_SLOT12_JS_HEAD_NEXT_LO";
    no_mali_reg_name[1937] = "JOB_SLOT12_JS_HEAD_NEXT_HI";
    no_mali_reg_name[1940] = "JOB_SLOT12_JS_AFFINITY_NEXT_LO";
    no_mali_reg_name[1941] = "JOB_SLOT12_JS_AFFINITY_NEXT_HI";
    no_mali_reg_name[1942] = "JOB_SLOT12_JS_CONFIG_NEXT";
    no_mali_reg_name[1943] = "JOB_SLOT12_JS_XAFFINITY_NEXT";
    no_mali_reg_name[1944] = "JOB_SLOT12_JS_COMMAND_NEXT";
    no_mali_reg_name[1948] = "JOB_SLOT12_JS_FLUSH_ID_NEXT";
    no_mali_reg_name[1952] = "JOB_SLOT13_JS_HEAD_LO";
    no_mali_reg_name[1953] = "JOB_SLOT13_JS_HEAD_HI";
    no_mali_reg_name[1954] = "JOB_SLOT13_JS_TAIL_LO";
    no_mali_reg_name[1955] = "JOB_SLOT13_JS_TAIL_HI";
    no_mali_reg_name[1956] = "JOB_SLOT13_JS_AFFINITY_LO";
    no_mali_reg_name[1957] = "JOB_SLOT13_JS_AFFINITY_HI";
    no_mali_reg_name[1958] = "JOB_SLOT13_JS_CONFIG";
    no_mali_reg_name[1959] = "JOB_SLOT13_JS_XAFFINITY";
    no_mali_reg_name[1960] = "JOB_SLOT13_JS_COMMAND";
    no_mali_reg_name[1961] = "JOB_SLOT13_JS_STATUS";
    no_mali_reg_name[1968] = "JOB_SLOT13_JS_HEAD_NEXT_LO";
    no_mali_reg_name[1969] = "JOB_SLOT13_JS_HEAD_NEXT_HI";
    no_mali_reg_name[1972] = "JOB_SLOT13_JS_AFFINITY_NEXT_LO";
    no_mali_reg_name[1973] = "JOB_SLOT13_JS_AFFINITY_NEXT_HI";
    no_mali_reg_name[1974] = "JOB_SLOT13_JS_CONFIG_NEXT";
    no_mali_reg_name[1975] = "JOB_SLOT13_JS_XAFFINITY_NEXT";
    no_mali_reg_name[1976] = "JOB_SLOT13_JS_COMMAND_NEXT";
    no_mali_reg_name[1980] = "JOB_SLOT13_JS_FLUSH_ID_NEXT";
    no_mali_reg_name[1984] = "JOB_SLOT14_JS_HEAD_LO";
    no_mali_reg_name[1985] = "JOB_SLOT14_JS_HEAD_HI";
    no_mali_reg_name[1986] = "JOB_SLOT14_JS_TAIL_LO";
    no_mali_reg_name[1987] = "JOB_SLOT14_JS_TAIL_HI";
    no_mali_reg_name[1988] = "JOB_SLOT14_JS_AFFINITY_LO";
    no_mali_reg_name[1989] = "JOB_SLOT14_JS_AFFINITY_HI";
    no_mali_reg_name[1990] = "JOB_SLOT14_JS_CONFIG";
    no_mali_reg_name[1991] = "JOB_SLOT14_JS_XAFFINITY";
    no_mali_reg_name[1992] = "JOB_SLOT14_JS_COMMAND";
    no_mali_reg_name[1993] = "JOB_SLOT14_JS_STATUS";
    no_mali_reg_name[2000] = "JOB_SLOT14_JS_HEAD_NEXT_LO";
    no_mali_reg_name[2001] = "JOB_SLOT14_JS_HEAD_NEXT_HI";
    no_mali_reg_name[2004] = "JOB_SLOT14_JS_AFFINITY_NEXT_LO";
    no_mali_reg_name[2005] = "JOB_SLOT14_JS_AFFINITY_NEXT_HI";
    no_mali_reg_name[2006] = "JOB_SLOT14_JS_CONFIG_NEXT";
    no_mali_reg_name[2007] = "JOB_SLOT14_JS_XAFFINITY_NEXT";
    no_mali_reg_name[2008] = "JOB_SLOT14_JS_COMMAND_NEXT";
    no_mali_reg_name[2012] = "JOB_SLOT14_JS_FLUSH_ID_NEXT";
    no_mali_reg_name[2016] = "JOB_SLOT15_JS_HEAD_LO";
    no_mali_reg_name[2017] = "JOB_SLOT15_JS_HEAD_HI";
    no_mali_reg_name[2018] = "JOB_SLOT15_JS_TAIL_LO";
    no_mali_reg_name[2019] = "JOB_SLOT15_JS_TAIL_HI";
    no_mali_reg_name[2020] = "JOB_SLOT15_JS_AFFINITY_LO";
    no_mali_reg_name[2021] = "JOB_SLOT15_JS_AFFINITY_HI";
    no_mali_reg_name[2022] = "JOB_SLOT15_JS_CONFIG";
    no_mali_reg_name[2023] = "JOB_SLOT15_JS_XAFFINITY";
    no_mali_reg_name[2024] = "JOB_SLOT15_JS_COMMAND";
    no_mali_reg_name[2025] = "JOB_SLOT15_JS_STATUS";
    no_mali_reg_name[2032] = "JOB_SLOT15_JS_HEAD_NEXT_LO";
    no_mali_reg_name[2033] = "JOB_SLOT15_JS_HEAD_NEXT_HI";
    no_mali_reg_name[2036] = "JOB_SLOT15_JS_AFFINITY_NEXT_LO";
    no_mali_reg_name[2037] = "JOB_SLOT15_JS_AFFINITY_NEXT_HI";
    no_mali_reg_name[2038] = "JOB_SLOT15_JS_CONFIG_NEXT";
    no_mali_reg_name[2039] = "JOB_SLOT15_JS_XAFFINITY_NEXT";
    no_mali_reg_name[2040] = "JOB_SLOT15_JS_COMMAND_NEXT";
    no_mali_reg_name[2044] = "JOB_SLOT15_JS_FLUSH_ID_NEXT";


    no_mali_reg_name[2048] = "MMU_IRQ_RAWSTAT";
    no_mali_reg_name[2049] = "MMU_IRQ_CLEAR";
    no_mali_reg_name[2050] = "MMU_IRQ_MASK";
    no_mali_reg_name[2051] = "MMU_IRQ_STATUS";

    no_mali_reg_name[2304] = "MMU_AS0_AS_TRANSTAB_LO";
    no_mali_reg_name[2305] = "MMU_AS0_AS_TRANSTAB_HI";
    no_mali_reg_name[2306] = "MMU_AS0_AS_MEMATTR_LO";
    no_mali_reg_name[2307] = "MMU_AS0_AS_MEMATTR_HI";
    no_mali_reg_name[2308] = "MMU_AS0_AS_LOCKADDR_LO";
    no_mali_reg_name[2309] = "MMU_AS0_AS_LOCKADDR_HI";
    no_mali_reg_name[2310] = "MMU_AS0_AS_COMMAND";
    no_mali_reg_name[2311] = "MMU_AS0_AS_FAULTSTATUS";
    no_mali_reg_name[2312] = "MMU_AS0_AS_FAULTADDRESS_LO";
    no_mali_reg_name[2313] = "MMU_AS0_AS_FAULTADDRESS_HI";
    no_mali_reg_name[2314] = "MMU_AS0_AS_STATUS";
    no_mali_reg_name[2320] = "MMU_AS1_AS_TRANSTAB_LO";
    no_mali_reg_name[2321] = "MMU_AS1_AS_TRANSTAB_HI";
    no_mali_reg_name[2322] = "MMU_AS1_AS_MEMATTR_LO";
    no_mali_reg_name[2323] = "MMU_AS1_AS_MEMATTR_HI";
    no_mali_reg_name[2324] = "MMU_AS1_AS_LOCKADDR_LO";
    no_mali_reg_name[2325] = "MMU_AS1_AS_LOCKADDR_HI";
    no_mali_reg_name[2326] = "MMU_AS1_AS_COMMAND";
    no_mali_reg_name[2327] = "MMU_AS1_AS_FAULTSTATUS";
    no_mali_reg_name[2328] = "MMU_AS1_AS_FAULTADDRESS_LO";
    no_mali_reg_name[2329] = "MMU_AS1_AS_FAULTADDRESS_HI";
    no_mali_reg_name[2330] = "MMU_AS1_AS_STATUS";
    no_mali_reg_name[2336] = "MMU_AS2_AS_TRANSTAB_LO";
    no_mali_reg_name[2337] = "MMU_AS2_AS_TRANSTAB_HI";
    no_mali_reg_name[2338] = "MMU_AS2_AS_MEMATTR_LO";
    no_mali_reg_name[2339] = "MMU_AS2_AS_MEMATTR_HI";
    no_mali_reg_name[2340] = "MMU_AS2_AS_LOCKADDR_LO";
    no_mali_reg_name[2341] = "MMU_AS2_AS_LOCKADDR_HI";
    no_mali_reg_name[2342] = "MMU_AS2_AS_COMMAND";
    no_mali_reg_name[2343] = "MMU_AS2_AS_FAULTSTATUS";
    no_mali_reg_name[2344] = "MMU_AS2_AS_FAULTADDRESS_LO";
    no_mali_reg_name[2345] = "MMU_AS2_AS_FAULTADDRESS_HI";
    no_mali_reg_name[2346] = "MMU_AS2_AS_STATUS";
    no_mali_reg_name[2352] = "MMU_AS3_AS_TRANSTAB_LO";
    no_mali_reg_name[2353] = "MMU_AS3_AS_TRANSTAB_HI";
    no_mali_reg_name[2354] = "MMU_AS3_AS_MEMATTR_LO";
    no_mali_reg_name[2355] = "MMU_AS3_AS_MEMATTR_HI";
    no_mali_reg_name[2356] = "MMU_AS3_AS_LOCKADDR_LO";
    no_mali_reg_name[2357] = "MMU_AS3_AS_LOCKADDR_HI";
    no_mali_reg_name[2358] = "MMU_AS3_AS_COMMAND";
    no_mali_reg_name[2359] = "MMU_AS3_AS_FAULTSTATUS";
    no_mali_reg_name[2360] = "MMU_AS3_AS_FAULTADDRESS_LO";
    no_mali_reg_name[2361] = "MMU_AS3_AS_FAULTADDRESS_HI";
    no_mali_reg_name[2362] = "MMU_AS3_AS_STATUS";
    no_mali_reg_name[2368] = "MMU_AS4_AS_TRANSTAB_LO";
    no_mali_reg_name[2369] = "MMU_AS4_AS_TRANSTAB_HI";
    no_mali_reg_name[2370] = "MMU_AS4_AS_MEMATTR_LO";
    no_mali_reg_name[2371] = "MMU_AS4_AS_MEMATTR_HI";
    no_mali_reg_name[2372] = "MMU_AS4_AS_LOCKADDR_LO";
    no_mali_reg_name[2373] = "MMU_AS4_AS_LOCKADDR_HI";
    no_mali_reg_name[2374] = "MMU_AS4_AS_COMMAND";
    no_mali_reg_name[2375] = "MMU_AS4_AS_FAULTSTATUS";
    no_mali_reg_name[2376] = "MMU_AS4_AS_FAULTADDRESS_LO";
    no_mali_reg_name[2377] = "MMU_AS4_AS_FAULTADDRESS_HI";
    no_mali_reg_name[2378] = "MMU_AS4_AS_STATUS";
    no_mali_reg_name[2384] = "MMU_AS5_AS_TRANSTAB_LO";
    no_mali_reg_name[2385] = "MMU_AS5_AS_TRANSTAB_HI";
    no_mali_reg_name[2386] = "MMU_AS5_AS_MEMATTR_LO";
    no_mali_reg_name[2387] = "MMU_AS5_AS_MEMATTR_HI";
    no_mali_reg_name[2388] = "MMU_AS5_AS_LOCKADDR_LO";
    no_mali_reg_name[2389] = "MMU_AS5_AS_LOCKADDR_HI";
    no_mali_reg_name[2390] = "MMU_AS5_AS_COMMAND";
    no_mali_reg_name[2391] = "MMU_AS5_AS_FAULTSTATUS";
    no_mali_reg_name[2392] = "MMU_AS5_AS_FAULTADDRESS_LO";
    no_mali_reg_name[2393] = "MMU_AS5_AS_FAULTADDRESS_HI";
    no_mali_reg_name[2394] = "MMU_AS5_AS_STATUS";
    no_mali_reg_name[2400] = "MMU_AS6_AS_TRANSTAB_LO";
    no_mali_reg_name[2401] = "MMU_AS6_AS_TRANSTAB_HI";
    no_mali_reg_name[2402] = "MMU_AS6_AS_MEMATTR_LO";
    no_mali_reg_name[2403] = "MMU_AS6_AS_MEMATTR_HI";
    no_mali_reg_name[2404] = "MMU_AS6_AS_LOCKADDR_LO";
    no_mali_reg_name[2405] = "MMU_AS6_AS_LOCKADDR_HI";
    no_mali_reg_name[2406] = "MMU_AS6_AS_COMMAND";
    no_mali_reg_name[2407] = "MMU_AS6_AS_FAULTSTATUS";
    no_mali_reg_name[2408] = "MMU_AS6_AS_FAULTADDRESS_LO";
    no_mali_reg_name[2409] = "MMU_AS6_AS_FAULTADDRESS_HI";
    no_mali_reg_name[2410] = "MMU_AS6_AS_STATUS";
    no_mali_reg_name[2416] = "MMU_AS7_AS_TRANSTAB_LO";
    no_mali_reg_name[2417] = "MMU_AS7_AS_TRANSTAB_HI";
    no_mali_reg_name[2418] = "MMU_AS7_AS_MEMATTR_LO";
    no_mali_reg_name[2419] = "MMU_AS7_AS_MEMATTR_HI";
    no_mali_reg_name[2420] = "MMU_AS7_AS_LOCKADDR_LO";
    no_mali_reg_name[2421] = "MMU_AS7_AS_LOCKADDR_HI";
    no_mali_reg_name[2422] = "MMU_AS7_AS_COMMAND";
    no_mali_reg_name[2423] = "MMU_AS7_AS_FAULTSTATUS";
    no_mali_reg_name[2424] = "MMU_AS7_AS_FAULTADDRESS_LO";
    no_mali_reg_name[2425] = "MMU_AS7_AS_FAULTADDRESS_HI";
    no_mali_reg_name[2426] = "MMU_AS7_AS_STATUS";
    no_mali_reg_name[2432] = "MMU_AS8_AS_TRANSTAB_LO";
    no_mali_reg_name[2433] = "MMU_AS8_AS_TRANSTAB_HI";
    no_mali_reg_name[2434] = "MMU_AS8_AS_MEMATTR_LO";
    no_mali_reg_name[2435] = "MMU_AS8_AS_MEMATTR_HI";
    no_mali_reg_name[2436] = "MMU_AS8_AS_LOCKADDR_LO";
    no_mali_reg_name[2437] = "MMU_AS8_AS_LOCKADDR_HI";
    no_mali_reg_name[2438] = "MMU_AS8_AS_COMMAND";
    no_mali_reg_name[2439] = "MMU_AS8_AS_FAULTSTATUS";
    no_mali_reg_name[2440] = "MMU_AS8_AS_FAULTADDRESS_LO";
    no_mali_reg_name[2441] = "MMU_AS8_AS_FAULTADDRESS_HI";
    no_mali_reg_name[2442] = "MMU_AS8_AS_STATUS";
    no_mali_reg_name[2448] = "MMU_AS9_AS_TRANSTAB_LO";
    no_mali_reg_name[2449] = "MMU_AS9_AS_TRANSTAB_HI";
    no_mali_reg_name[2450] = "MMU_AS9_AS_MEMATTR_LO";
    no_mali_reg_name[2451] = "MMU_AS9_AS_MEMATTR_HI";
    no_mali_reg_name[2452] = "MMU_AS9_AS_LOCKADDR_LO";
    no_mali_reg_name[2453] = "MMU_AS9_AS_LOCKADDR_HI";
    no_mali_reg_name[2454] = "MMU_AS9_AS_COMMAND";
    no_mali_reg_name[2455] = "MMU_AS9_AS_FAULTSTATUS";
    no_mali_reg_name[2456] = "MMU_AS9_AS_FAULTADDRESS_LO";
    no_mali_reg_name[2457] = "MMU_AS9_AS_FAULTADDRESS_HI";
    no_mali_reg_name[2458] = "MMU_AS9_AS_STATUS";
    no_mali_reg_name[2464] = "MMU_AS10_AS_TRANSTAB_LO";
    no_mali_reg_name[2465] = "MMU_AS10_AS_TRANSTAB_HI";
    no_mali_reg_name[2466] = "MMU_AS10_AS_MEMATTR_LO";
    no_mali_reg_name[2467] = "MMU_AS10_AS_MEMATTR_HI";
    no_mali_reg_name[2468] = "MMU_AS10_AS_LOCKADDR_LO";
    no_mali_reg_name[2469] = "MMU_AS10_AS_LOCKADDR_HI";
    no_mali_reg_name[2470] = "MMU_AS10_AS_COMMAND";
    no_mali_reg_name[2471] = "MMU_AS10_AS_FAULTSTATUS";
    no_mali_reg_name[2472] = "MMU_AS10_AS_FAULTADDRESS_LO";
    no_mali_reg_name[2473] = "MMU_AS10_AS_FAULTADDRESS_HI";
    no_mali_reg_name[2474] = "MMU_AS10_AS_STATUS";
    no_mali_reg_name[2480] = "MMU_AS11_AS_TRANSTAB_LO";
    no_mali_reg_name[2481] = "MMU_AS11_AS_TRANSTAB_HI";
    no_mali_reg_name[2482] = "MMU_AS11_AS_MEMATTR_LO";
    no_mali_reg_name[2483] = "MMU_AS11_AS_MEMATTR_HI";
    no_mali_reg_name[2484] = "MMU_AS11_AS_LOCKADDR_LO";
    no_mali_reg_name[2485] = "MMU_AS11_AS_LOCKADDR_HI";
    no_mali_reg_name[2486] = "MMU_AS11_AS_COMMAND";
    no_mali_reg_name[2487] = "MMU_AS11_AS_FAULTSTATUS";
    no_mali_reg_name[2488] = "MMU_AS11_AS_FAULTADDRESS_LO";
    no_mali_reg_name[2489] = "MMU_AS11_AS_FAULTADDRESS_HI";
    no_mali_reg_name[2490] = "MMU_AS11_AS_STATUS";
    no_mali_reg_name[2496] = "MMU_AS12_AS_TRANSTAB_LO";
    no_mali_reg_name[2497] = "MMU_AS12_AS_TRANSTAB_HI";
    no_mali_reg_name[2498] = "MMU_AS12_AS_MEMATTR_LO";
    no_mali_reg_name[2499] = "MMU_AS12_AS_MEMATTR_HI";
    no_mali_reg_name[2500] = "MMU_AS12_AS_LOCKADDR_LO";
    no_mali_reg_name[2501] = "MMU_AS12_AS_LOCKADDR_HI";
    no_mali_reg_name[2502] = "MMU_AS12_AS_COMMAND";
    no_mali_reg_name[2503] = "MMU_AS12_AS_FAULTSTATUS";
    no_mali_reg_name[2504] = "MMU_AS12_AS_FAULTADDRESS_LO";
    no_mali_reg_name[2505] = "MMU_AS12_AS_FAULTADDRESS_HI";
    no_mali_reg_name[2506] = "MMU_AS12_AS_STATUS";
    no_mali_reg_name[2512] = "MMU_AS13_AS_TRANSTAB_LO";
    no_mali_reg_name[2513] = "MMU_AS13_AS_TRANSTAB_HI";
    no_mali_reg_name[2514] = "MMU_AS13_AS_MEMATTR_LO";
    no_mali_reg_name[2515] = "MMU_AS13_AS_MEMATTR_HI";
    no_mali_reg_name[2516] = "MMU_AS13_AS_LOCKADDR_LO";
    no_mali_reg_name[2517] = "MMU_AS13_AS_LOCKADDR_HI";
    no_mali_reg_name[2518] = "MMU_AS13_AS_COMMAND";
    no_mali_reg_name[2519] = "MMU_AS13_AS_FAULTSTATUS";
    no_mali_reg_name[2520] = "MMU_AS13_AS_FAULTADDRESS_LO";
    no_mali_reg_name[2521] = "MMU_AS13_AS_FAULTADDRESS_HI";
    no_mali_reg_name[2522] = "MMU_AS13_AS_STATUS";
    no_mali_reg_name[2528] = "MMU_AS14_AS_TRANSTAB_LO";
    no_mali_reg_name[2529] = "MMU_AS14_AS_TRANSTAB_HI";
    no_mali_reg_name[2530] = "MMU_AS14_AS_MEMATTR_LO";
    no_mali_reg_name[2531] = "MMU_AS14_AS_MEMATTR_HI";
    no_mali_reg_name[2532] = "MMU_AS14_AS_LOCKADDR_LO";
    no_mali_reg_name[2533] = "MMU_AS14_AS_LOCKADDR_HI";
    no_mali_reg_name[2534] = "MMU_AS14_AS_COMMAND";
    no_mali_reg_name[2535] = "MMU_AS14_AS_FAULTSTATUS";
    no_mali_reg_name[2536] = "MMU_AS14_AS_FAULTADDRESS_LO";
    no_mali_reg_name[2537] = "MMU_AS14_AS_FAULTADDRESS_HI";
    no_mali_reg_name[2538] = "MMU_AS14_AS_STATUS";
    no_mali_reg_name[2544] = "MMU_AS15_AS_TRANSTAB_LO";
    no_mali_reg_name[2545] = "MMU_AS15_AS_TRANSTAB_HI";
    no_mali_reg_name[2546] = "MMU_AS15_AS_MEMATTR_LO";
    no_mali_reg_name[2547] = "MMU_AS15_AS_MEMATTR_HI";
    no_mali_reg_name[2548] = "MMU_AS15_AS_LOCKADDR_LO";
    no_mali_reg_name[2549] = "MMU_AS15_AS_LOCKADDR_HI";
    no_mali_reg_name[2550] = "MMU_AS15_AS_COMMAND";
    no_mali_reg_name[2551] = "MMU_AS15_AS_FAULTSTATUS";
    no_mali_reg_name[2552] = "MMU_AS15_AS_FAULTADDRESS_LO";
    no_mali_reg_name[2553] = "MMU_AS15_AS_FAULTADDRESS_HI";
    no_mali_reg_name[2554] = "MMU_AS15_AS_STATUS";

}

